openapi: '3.0.2'
info:
  title: CTU Group 2 Pizza Ordering System
  description: >-
    This is an OpenAPI spec for the backend of the Pizza Ordering System for the
    CTU 2023 CS491 Group Project for Group 2.
  version: '1.0'
servers:
  - url: http://localhost

components:
  schemas:
    User:
      type: object
      properties:
        property:
          type: integer
paths:
  /user:
    summary: /user
    description: Used for managing users as well as user login
    post:
      summary: Create User
      description: Path creates a user. Body must contain a Username and Password.
      operationId: post_users
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              examples:
                Success:
                  value: |-
                    {
                        "created": true,
                        "reason": "Success"
                    }
        '409':
          description: User cannot be created (Duplicate Username)
          content:
            application/json:
              examples:
                Failure:
                  value: |-
                    {
                        "created": false,
                        "reason": "User Already Exists with Username"
                    }
        '400':
          description: User cannot be created (Missing Body Components)
          content:
            application/json:
              examples:
                Failure:
                  value: |-
                    {
                        "created": false,
                        "reason": "Body Missing Username and/or Password"
                    }
      tags:
        - user
    get:
      summary: Retrieve All Users
      description: Path retrieves all users. Partial data returned if user is not authenitcated.
      operationId: get_users
      responses:
        '200':
          description: Users retrieved
          content: 
            application/json:
              examples:
                Success:
                  value: |-
                    {
                        ""
                    }


tags:
  - name: user
    description: Base User class
  - name: customer
    description: Customer class extends User, includes Payments and Orders
  - name: pizza
    description: Pizza class, has Ingredients and is associated to Orders
  - name: ingredient
    description: Ingredient class
  - name: order
    description: >-
      Order class, contains a Payment, Address, Pizzas, and is associated to
      Users
  - name: payment
    description: Payment Methods, associated to Users and Orders
  - name: address
    description: Addresses, either billing or shipping, associated to Payments and Users
  - name: promo
    description: Promotions, associated to Orders